### ISSUE TITLE
安装并开启脚本 页面上看不到那些配置项是怎么回事

### ISSUE THREAD

**Issue by w78265118** [yongjiu8/boss_push#2]

**Comment by w78265118** [comment]
console一直在初始化 const jobSearchWrapper = document.querySelector(".job-search-wrapper")

这行代码 jobSearchWrapper 为null

**Comment by yongjiu8** [comment]
首页点进去岗位页面才会出来

**Comment by yongjiu8** [comment]
https://www.zhipin.com/web/geek/job?query=&city=101280100&position=100101
